### ISSUE TITLE
Performance regression when upgrading to 0.7.0

### ISSUE THREAD

**Issue by DomNomNom** [Qiskit-Partners/mapomatic#56]
Running the following code on 0.6.0 is drastically faster than the latest version.

```py
import time

import mapomatic
from qiskit import QuantumCircuit
from qiskit.providers.fake_provider import FakeGuadalupe

print("mapomatic version", mapomatic.__version__)

print("0", time.perf_counter())
qc = QuantumCircuit(7)
qc.measure_all()
backend = FakeGuadalupe()

print("1", time.perf_counter())
reduced_circuit = mapomatic.deflate_circuit(qc)
print("2", time.perf_counter())
possible_layouts = mapomatic.matching_layouts(reduced_circuit, backend)
print("3", time.perf_counter())
heuristic_scores = mapomatic.evaluate_layouts(
    reduced_circuit, possible_layouts, backend
)
print("4", time.perf_counter())
```

```
mapomatic version 0.6.0
0 0.464177369
1 0.930080825
2 0.93067732
3 1.453258124
4 2.484866645
```

```
mapomatic version 0.7.0
0 0.718068748
1 1.386374567
2 1.386823443
3 161.074256214
4 543.190371104
```

**Comment by DomNomNom** [comment]
Alright. it would be good if that gets ported in as it is currently blocking an upgrade for us.

**Comment by nonhermitian** [comment]
Just to follow up here.  The slow down that you are seeing is actually most likely coming from the increase in the `call_limit` that is needed for getting most, if not all, of the layouts at larger qubit counts:

https://github.com/Qiskit-Partners/mapomatic/blob/6afeaa0a610470246ce4666f319a2e603e56c223/mapomatic/layouts.py#L38

This can be tuned down to make the whole routine faster.

**Comment by DomNomNom** [comment]
ok, turning it down to what it used to be (100000) seems to make the performance match again.

**Comment by nonhermitian** [comment]
Closing as solved.
